const TIMEOUT = 100000;
const CLICK_TIMEOUT = 15000;
const DROPDOWN_ATTEMPTS = 10;
const ENABLE_SHARE_PRICE_VALIDATION = true;
const PRICE_TOLERANCE = 1;
const SCRAPE_RETRY_ATTEMPTS = 4;
const SCRAPE_RETRY_DELAY_MS = 4000;
const SHARE_PRICE_SCRAPE_ATTEMPTS = 3;
const SHARE_PRICE_SCRAPE_RETRY_DELAY_MS = 3000;

module.exports = {
  TIMEOUT,
  CLICK_TIMEOUT,
  DROPDOWN_ATTEMPTS,
  ENABLE_SHARE_PRICE_VALIDATION,
  PRICE_TOLERANCE,
  SCRAPE_RETRY_ATTEMPTS,
  SCRAPE_RETRY_DELAY_MS,
  SHARE_PRICE_SCRAPE_ATTEMPTS,
  SHARE_PRICE_SCRAPE_RETRY_DELAY_MS
};
